//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public int NUSP { get; set; }
        public string Telefone { get; set; }
        public int Curso { get; set; }
        public string Unidade { get; set; }
    
        public virtual Curso Curso1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
