//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Estagio = new HashSet<Estagio>();
            this.Curso = new HashSet<Curso>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
    
        public virtual Area Area1 { get; set; }
        public virtual Area Area2 { get; set; }
        public virtual ICollection<Estagio> Estagio { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
    }
}
