//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Aluno = new HashSet<Aluno>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Area { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual Area Area1 { get; set; }
    }
}
