//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPeriodico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class estagioEntities : DbContext
    {
        public estagioEntities()
            : base("name=estagioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Estagio> Estagio { get; set; }
    
        public virtual int EstagioDeletar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstagioDeletar", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> EstagioInsert(Nullable<int> empresaID, string descricao, string breveDescricao, Nullable<System.DateTime> dataInicio, Nullable<int> duracao, string bolsa, Nullable<int> area)
        {
            var empresaIDParameter = empresaID.HasValue ?
                new ObjectParameter("empresaID", empresaID) :
                new ObjectParameter("empresaID", typeof(int));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("descricao", descricao) :
                new ObjectParameter("descricao", typeof(string));
    
            var breveDescricaoParameter = breveDescricao != null ?
                new ObjectParameter("breveDescricao", breveDescricao) :
                new ObjectParameter("breveDescricao", typeof(string));
    
            var dataInicioParameter = dataInicio.HasValue ?
                new ObjectParameter("dataInicio", dataInicio) :
                new ObjectParameter("dataInicio", typeof(System.DateTime));
    
            var duracaoParameter = duracao.HasValue ?
                new ObjectParameter("duracao", duracao) :
                new ObjectParameter("duracao", typeof(int));
    
            var bolsaParameter = bolsa != null ?
                new ObjectParameter("bolsa", bolsa) :
                new ObjectParameter("bolsa", typeof(string));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("EstagioInsert", empresaIDParameter, descricaoParameter, breveDescricaoParameter, dataInicioParameter, duracaoParameter, bolsaParameter, areaParameter);
        }
    
        public virtual int EstagioUpdate(Nullable<int> empresaID, string descricao, string breveDescricao, Nullable<System.DateTime> dataInicio, Nullable<int> duracao, string bolsa, Nullable<int> area, Nullable<int> id)
        {
            var empresaIDParameter = empresaID.HasValue ?
                new ObjectParameter("empresaID", empresaID) :
                new ObjectParameter("empresaID", typeof(int));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("descricao", descricao) :
                new ObjectParameter("descricao", typeof(string));
    
            var breveDescricaoParameter = breveDescricao != null ?
                new ObjectParameter("breveDescricao", breveDescricao) :
                new ObjectParameter("breveDescricao", typeof(string));
    
            var dataInicioParameter = dataInicio.HasValue ?
                new ObjectParameter("dataInicio", dataInicio) :
                new ObjectParameter("dataInicio", typeof(System.DateTime));
    
            var duracaoParameter = duracao.HasValue ?
                new ObjectParameter("duracao", duracao) :
                new ObjectParameter("duracao", typeof(int));
    
            var bolsaParameter = bolsa != null ?
                new ObjectParameter("bolsa", bolsa) :
                new ObjectParameter("bolsa", typeof(string));
    
            var areaParameter = area.HasValue ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstagioUpdate", empresaIDParameter, descricaoParameter, breveDescricaoParameter, dataInicioParameter, duracaoParameter, bolsaParameter, areaParameter, idParameter);
        }
    }
}
