//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoCEPE
    {
        public int ID { get; set; }
        public int AlunoID { get; set; }
        public string Local { get; set; }
        public string Esporte { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Horario { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    }
}
