//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class palestras
    {
        public int ID { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string imagemLink { get; set; }
        public Nullable<bool> valido { get; set; }
        public Nullable<System.DateTime> dataModificacao { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public string duracao { get; set; }
        public string local { get; set; }
        public string palestrantes { get; set; }
    }
}
